[workspace]
members = [
    "heim",
    "heim-common",
    "heim-host",
    "heim-cpu",
    "heim-derive",
    "heim-memory",
    "heim-disk",
#    "heim-net",
#    "heim-process",
#    "heim-virt",
#    "heim-winservice",
]


[patch.crates-io]
runtime = { git = "https://github.com/taiki-e/runtime", branch = "await" }
romio = { git = "https://github.com/dbcfd/romio", branch = "futures-changes" }
juliex = { git = "https://github.com/taiki-e/juliex", branch = "await" }
