[package]
name = "heim-process"
version = "0.0.7"
authors = ["svartalf <self@svartalf.info>"]
edition = "2018"
description = "Cross-platform processes information"
keywords = ["heim", "system", "process", "pid"]
categories = ["asynchronous", "os", "api-bindings"]
repository = "https://github.com/heim-rs/heim"
readme = "README.md"
license = "Apache-2.0 OR MIT"

[badges]
maintenance = { status = "experimental" }
azure-devops = { project = "heim-rs/heim", pipeline = "heim-rs.heim" }

[dependencies]
heim-derive = { version = "0.0.7", path = "../heim-derive" }
heim-common = { version = "0.0.7", path = "../heim-common" }
heim-runtime = { version = "0.0.3", path = "../heim-runtime" }
heim-cpu = { version = "0.0.7", path = "../heim-cpu" }
cfg-if = "0.1.7"
libc = "~0.2"
futures-preview = "0.3.0-alpha.18"
lazy_static = "1.3.0"

[target.'cfg(target_os = "linux")'.dependencies]
heim-net = { version = "0.0.7", path = "../heim-net" }

[target.'cfg(target_os = "windows")'.dependencies]
ntapi = "0.3.3"

[target.'cfg(target_os = "windows")'.dependencies.winapi]
version = ">=0.3.8"
default-features = false
features = [
    "impl-default",
    "minwindef",
    "winnt",
    "winbase",
    "handleapi",
    "psapi",
    "processthreadsapi",
    "winerror",
    "tlhelp32"
]

[target.'cfg(target_os = "macos")'.dependencies]
mach = "0.3.2"
darwin-libproc = "0.1.1"

[dev-dependencies]
version-sync = "0.8"
pin-utils = "0.1.0-alpha.4"
futures-timer = "0.3.0"

[features]
runtime-polyfill = ["heim-runtime/runtime-polyfill"]
