[package]
name = "heim-process"
version = "0.0.5"
authors = ["svartalf <self@svartalf.info>"]
edition = "2018"
description = "Cross-platform processes information"
keywords = ["heim", "system", "process", "pid"]
categories = ["asynchronous", "os", "api-bindings"]
repository = "https://github.com/heim-rs/heim"
readme = "README.md"
license = "Apache-2.0 OR MIT"

[badges]
maintenance = { status = "experimental" }
azure-devops = { project = "heim-rs", pipeline = "heim" }

[dependencies]
heim-derive = { version = "0.0.5", path = "../heim-derive" }
heim-common = { version = "0.0.5", path = "../heim-common" }
heim-runtime = { version = "0.0.2", path = "../heim-runtime" }
cfg-if = "0.1.7"
libc = "0.2.58"

[target.'cfg(target_os = "windows")'.dependencies.winapi]
version = "0.3.7"
default-features = false
features = [
    "minwindef",
    "winnt",
    "handleapi",
    "psapi",
    "processthreadsapi",
    "winerror"
]

[target.'cfg(target_os = "macos")'.dependencies]
mach = "0.3.2"

[dev-dependencies]
runtime = "0.3.0-alpha.6"
version-sync = "0.8"

[features]
reactor-polyfill = ["heim-runtime/reactor-polyfill"]
