[package]
name = "heim-cpu"
version = "0.0.3"
authors = ["svartalf <self@svartalf.info>"]
edition = "2018"
description = "Cross-platform CPU information"
keywords = ["heim", "system", "cpu", "information"]
categories = ["asynchronous", "os"]
repository = "https://github.com/heim-rs/heim"
readme = "README.md"
license = "Apache-2.0 OR MIT"

[badges]
maintenance = { status = "experimental" }

[dependencies]
heim-derive = { version = "0.0.3", path = "../heim-derive" }
heim-common = { version = "0.0.3", path = "../heim-common" }
lazy_static = "1.3.0"
cfg-if = "0.1.7"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.58"
glob = "0.3.0"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.7", features = ["powerbase", "sysinfoapi", "winnt", "processthreadsapi", "impl-default"] }

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2.58"
mach = "0.3.2"

[dev-dependencies]
runtime = "0.3.0-alpha.6"

[features]
doc = []

[package.metadata.docs.rs]
features = ["doc"]
