[package]
name = "heim-common"
version = "0.0.2"
authors = ["svartalf <self@svartalf.info>"]
edition = "2018"
description = "Common stuff shared across heim project crates"
keywords = ["heim", "system", "information"]
categories = ["asynchronous", "os"]
repository = "https://github.com/heim-rs/heim"
readme = "README.md"
license = "Apache-2.0 OR MIT"

[badges]
maintenance = { status = "experimental" }

[dependencies]
heim-derive = { version = "0.0.2", path = "../heim-derive" }
cfg-if = "0.1.7"
try_from = "0.3.2"
runtime = "0.3.0-alpha.3"
futures-preview = "0.3.0-alpha.16"

[dev-dependencies]
criterion = "0.2.10"

[target.'cfg(unix)'.dependencies]
nix = "0.13.0"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.7", features = ["winnt", "minwindef"] }

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2.53"
mach = "0.2.3"
core-foundation = "0.6.4"

[features]
doc = []

[package.metadata.docs.rs]
features = ["doc"]
