[package]
name = "heim-net"
version = "0.0.9"
authors = ["svartalf <self@svartalf.info>"]
edition = "2018"
description = "Cross-platform network information"
keywords = ["heim", "system", "network", "connections", "nic"]
categories = ["asynchronous", "os", "api-bindings"]
repository = "https://github.com/heim-rs/heim"
readme = "README.md"
license = "Apache-2.0 OR MIT"

[badges]
maintenance = { status = "experimental" }
azure-devops = { project = "heim-rs/heim", pipeline = "heim-rs.heim" }

[dependencies]
heim-derive = { version = "0.0.9", path = "../heim-derive" }
heim-common = { version = "0.0.9", path = "../heim-common" }
heim-runtime = { version = "0.0.5", path = "../heim-runtime" }
cfg-if = "0.1.7"
bitflags = "1.0.4"
macaddr = "1.0"
libc = "~0.2"

[dev-dependencies]
futures-executor = "^0.3"
version-sync = "0.8"

[target.'cfg(unix)'.dependencies]
nix = "0.16.0"

[target.'cfg(target_os = "linux")'.dependencies]
hex = "0.4.0"

[features]
runtime-polyfill = ["heim-runtime/runtime-polyfill"]
