[package]
name = "heim-virt"
version = "0.0.7"
authors = ["svartalf <self@svartalf.info>"]
edition = "2018"
description = "Cross-platform virtualization system detection"
keywords = ["heim", "system", "information"]
categories = ["asynchronous", "os", "api-bindings"]
repository = "https://github.com/heim-rs/heim"
readme = "README.md"
license = "Apache-2.0 OR MIT"

[badges]
maintenance = { status = "experimental" }
azure-devops = { project = "heim-rs/heim", pipeline = "heim-rs.heim" }

[dependencies]
heim-common = { version = "0.0.7", path = "../heim-common" }
heim-runtime = { version = "0.0.3", path = "../heim-runtime" }
cfg-if = "0.1.9"

[target.'cfg(target_os = "linux")'.dependencies]
raw-cpuid = "6.1.0"

[dev-dependencies]
heim-derive = { version = "0.0.7", path = "../heim-derive" }
futures-preview = "0.3.0-alpha.18"
version-sync = "0.8"
tempfile = "3.0"

[features]
runtime-polyfill = ["heim-runtime/runtime-polyfill"]
